[package]
name = "advect2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heatmap_anim = { path = "../../../libs/heatmap_anim"}
mpi = "0.6"
